### ISSUE TITLE
How to make it to support conversation memories?

### ISSUE THREAD

**Issue by eric2788** [PullRequestInc/go-gpt3#15]
I followed the example from readme but i found that the chat didn't remember the previous conversation, how should I do it?

**Comment by tylermann** [comment]
Hi @eric2788 , I don't believe that functionality exists by itself in the current gpt-3 APIs.

If you are referencing the way that ChatGPT works and remembers previous comments, I believe that is specific behavior to ChatGPT which is built on top of gpt-3, but not just purely using gpt-3 APIs

One way to achieve this type of behavior would be using "prompt engineering" and pass some of the previous inputs/outputs at the start of your prompt to give it some "memory", but this would be outside of the scope of this library which is meant to just be a Go interface to the APIs, so I will close this issue. Although if you are referencing something else that you can do with the API or playground but doesn't work here, then feel free to reopen.

**Comment by eric2788** [comment]
I have already found that kind of library, thank you anyways
