### ISSUE TITLE
New ChatGPT and Whisper APIs

### ISSUE THREAD

**Issue by JoshuaFurman** [PullRequestInc/go-gpt3#29]
Based on this blog post: https://openai.com/blog/introducing-chatgpt-and-whisper-apis
2 new APIs have been made available:
- ChatGPT
- Whisper

I realize these APIs were just made public today but was wondering if there is the intention of including them into this library?

**Comment by sashabaranov** [comment]
Shameless plug: we support ChatGPT here https://github.com/sashabaranov/go-gpt3

**Comment by JoshuaFurman** [comment]
Ahh thank you. I began writing a PR for that repo but looks like you beat me to it :)

**Comment by tylermann** [comment]
The ChatGPT APIs should be in the latest version of this API now, however Whisper isn't currently supported. I'm not sure how much interest there is in Whisper being added to this framework.

Perhaps could open a separate issue if we want to track that specifically. It is somewhat beyond the original intent to support the language/completion usecases. @sashabaranov's library mentioned above may be the better option there as it is supporting things like dalle-2 and whisper.
