### ISSUE TITLE
The Functions feature is causing the API to return [400:invalid_request_error]

### ISSUE THREAD

**Issue by doughdjoe** [PullRequestInc/go-gpt3#37]
#36 

I am using the `ChatCompletionRequest` endpoint, upgraded from `v1.1.15` to `v1.1.16` and I am now getting an error response from the API - I haven't done any other changes on my end.

`[400:invalid_request_error] None is not of type 'array' - 'functions'` 

I did not add any `Functions` to my request, and it doesn't seem that `Functions` is a required parameter, but somehow the API is now replying as if it was included in the request with the `None` value by default, and complaining that value is not of type array.

Adding an empty `Functions` parameter to the request and the API responds "correctly" with `[400:invalid_request_error] '' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'functions.0.name'`

I noticed that `Functions` support was recently added in the latest pull request but have not been able to figure out what is going wrong. Perhaps the API expects an empty array instead of the `None` value it is receiving or interpreting?

Rolling back to v1.1.15 fixes the issue.

**Comment by SadriShehu** [comment]
Any news on this one, I see that there is already a fix provided, is this going to be merged?
